[target.aarch64-apple-darwin]
image = "ghcr.io/cross-rs/aarch64-apple-darwin-cross:local"
env.passthrough = ["CFLAGS_aarch64_apple_darwin=-fuse-ld=/opt/osxcross/bin/aarch64-apple-darwin20.4-ld"]
pre-build = [
    "apt-get update",
    "apt-get install -y libssl-dev"
]