version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:25.3
    restart: always
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
      - CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS=true
    ports: 
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:8123:8123'
    volumes:
      - './install-bundle.sh:/docker-entrypoint-initdb.d/install-bundle.sh'
